// <auto-generated />
using System;
using EmailApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmailApp.Migrations.AlarmDb
{
    [DbContext(typeof(AlarmDbContext))]
    [Migration("20260330023221_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmailApp.Models.AlarmDetail", b =>
                {
                    b.Property<int>("AlarmDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlarmDetailId"));

                    b.Property<int>("AlarmId")
                        .HasColumnType("int");

                    b.Property<string>("AlarmState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmTransition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("OperatorID")
                        .HasColumnType("int");

                    b.Property<string>("OperatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorNode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<short?>("TransitionDaylightAdjustment")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("TransitionTime")
                        .HasColumnType("datetime2");

                    b.Property<short?>("TransitionTimeFracSec")
                        .HasColumnType("smallint");

                    b.Property<short?>("TransitionTimeZoneOffset")
                        .HasColumnType("smallint");

                    b.HasKey("AlarmDetailId");

                    b.HasIndex("AlarmId");

                    b.ToTable("AlarmDetail", (string)null);
                });

            modelBuilder.Entity("EmailApp.Models.AlarmMaster", b =>
                {
                    b.Property<int>("AlarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlarmId"));

                    b.Property<int?>("CauseId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OriginationTime")
                        .HasColumnType("datetime2");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlarmId");

                    b.ToTable("AlarmMaster", (string)null);
                });

            modelBuilder.Entity("EmailApp.Models.AlarmDetail", b =>
                {
                    b.HasOne("EmailApp.Models.AlarmMaster", "AlarmMaster")
                        .WithMany("AlarmDetails")
                        .HasForeignKey("AlarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmMaster");
                });

            modelBuilder.Entity("EmailApp.Models.AlarmMaster", b =>
                {
                    b.Navigation("AlarmDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
